apiVersion: apps/v1
kind: Deployment
metadata:
  name: codemate-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: codemate-backend
  template:
    metadata:
      labels:
        app: codemate-backend
    spec:
      containers:
        - name: codemate
          image: parthivsinhv/codemate-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5050
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "800m"
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: codemate-backend-config
                  key: PORT
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: codemate-backend-secrets
                  key: MONGO_URL
            - name: ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: codemate-backend-secrets
                  key: ACCESS_TOKEN_SECRET
            - name: ACCESS_TOKEN_EXPIRES_IN
              valueFrom:
                secretKeyRef:
                  name: codemate-backend-secrets
                  key: ACCESS_TOKEN_EXPIRES_IN
            - name: REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: codemate-backend-secrets
                  key: REFRESH_TOKEN_SECRET
            - name: REFRESH_TOKEN_EXPIRES_IN
              valueFrom:
                secretKeyRef:
                  name: codemate-backend-secrets
                  key: REFRESH_TOKEN_EXPIRES_IN
            - name: JUDGE0_API_KEY
              valueFrom:
                secretKeyRef:
                  name: codemate-backend-secrets
                  key: JUDGE0_API_KEY
            - name: JUDGE0_APP
              valueFrom:
                secretKeyRef:
                  name: codemate-backend-secrets
                  key: JUDGE0_APP
            - name: REQ_URL
              valueFrom:
                secretKeyRef:
                  name: codemate-backend-secrets
                  key: REQ_URL
            - name: JUDGE0_API_URL
              valueFrom:
                secretKeyRef:
                  name: codemate-backend-secrets
                  key: JUDGE0_API_URL
          volumeMounts:
            - name: stockfish-engine
              mountPath: /usr/src/app/engine
      volumes:
        - name: stockfish-engine
          emptyDir: {}
