apiVersion: v1
kind: Service
metadata:
  name: codemate-backend-service
spec:
  selector:
    app: codemate-backend
  ports:
    - port: 5050
      targetPort: 5050
      nodePort: 31001
  type: NodePort
