import { Markdown } from '../../../components/ui/Markdown'
import { Spinner } from '../../../components/ui/Spinner'
import type { AiReport, AiStatusValue } from '../../../types/api'
import { moveNumberLabel } from '../../../utils/format'

interface AiReportCardProps {
  report?: AiReport
  aiStatus: AiStatusValue
  onJump: (ply: number) => void
}

function List({ title, items, tone }: { title: string; items: string[]; tone: string }) {
  if (!items?.length) return null
  return (
    <section>
      <h3 className="mb-1 text-sm font-semibold">{title}</h3>
      <ul className="space-y-1 text-sm text-muted">
        {items.map((s, i) => (
          <li key={i} className="flex gap-2">
            <span className={tone} aria-hidden="true">
              •
            </span>
            <span>{s}</span>
          </li>
        ))}
      </ul>
    </section>
  )
}

/** The AI coach report for one game: summary, strengths, weaknesses, key moments, recommendations. */
export function AiReportCard({ report, aiStatus, onJump }: AiReportCardProps) {
  if (!report) {
    return (
      <div className="p-4 text-sm text-muted">
        {aiStatus === 'pending' ? (
          <span className="flex items-center gap-2">
            <Spinner /> The AI coach report is being written…
          </span>
        ) : aiStatus === 'skipped' ? (
          'No AI report for this game (no LLM configured). The engine analysis and the chat still work in engine-facts mode.'
        ) : aiStatus === 'failed' ? (
          "The AI report couldn't be generated. The engine analysis is still available."
        ) : (
          'No AI report yet.'
        )}
      </div>
    )
  }
  return (
    <div className="space-y-4 p-4">
      <Markdown>{report.summary}</Markdown>
      <List title="Strengths" items={report.strengths} tone="text-success" />
      <List title="Weaknesses" items={report.weaknesses} tone="text-danger" />
      {report.keyMoments?.length > 0 && (
        <section>
          <h3 className="mb-1 text-sm font-semibold">Key moments</h3>
          <ul className="space-y-2">
            {report.keyMoments.map((k) => (
              <li key={k.ply}>
                <button
                  type="button"
                  onClick={() => onJump(k.ply)}
                  className="w-full rounded-lg border border-line p-2.5 text-left text-sm hover:border-primary hover:bg-surface-2"
                >
                  <span className="font-mono font-medium">
                    {moveNumberLabel(k.ply)} {k.playedMove}
                  </span>
                  {k.bestMove && k.bestMove !== k.playedMove && <span className="text-xs text-muted"> · best {k.bestMove}</span>}
                  <span className="mt-0.5 block text-muted">{k.explanation}</span>
                </button>
              </li>
            ))}
          </ul>
        </section>
      )}
      <List title="Recommendations" items={report.trainingRecommendations} tone="text-primary" />
      <p className="text-[11px] text-subtle">
        {report.provider === 'none' ? 'Engine-facts mode (no LLM configured)' : `Generated by ${report.provider}${report.model ? ` · ${report.model}` : ''}`}
      </p>
    </div>
  )
}
